solarController:
  httpPort: 8080
  epever:
    serialPort: /dev/ttyXRUSB0
    publishPeriod: 60
  victron:
    macAddress:
    publishPeriod: 30
  mqtt:
    host:
    username:
    password:
    topicPrefix: solar/metrics